USE HMS;

DROP Procedure IF EXISTS DeleteNurse;
DELIMITER %%
CREATE PROCEDURE DeleteNurse (
	ID INT, 
    FN VARCHAR(20),
    LN VARCHAR(20)
)
BEGIN
	DELETE FROM NURSE WHERE nurseID = ID;
    DELETE FROM STAFF WHERE staffID = ID;
    DELETE FROM staffRecord WHERE isStaff = true AND isPatient=false AND staffID=ID AND firstName = FN AND lastName=LN;

END %%
DELIMITER ;

DROP Procedure IF EXISTS DeleteJanitor;
DELIMITER %%
CREATE PROCEDURE DeleteJanitor (
	ID INT, 
    FN VARCHAR(20),
    LN VARCHAR(20)
)
BEGIN
	DELETE FROM JANITOR WHERE janitorID = ID;
    DELETE FROM STAFF WHERE staffID = ID;
    DELETE FROM staffRecord WHERE isStaff = true AND isPatient=false AND staffID=ID AND firstName = FN AND lastName=LN;

END %%
DELIMITER ;

DROP Procedure IF EXISTS DeleteCashier;
DELIMITER %%
CREATE PROCEDURE DeleteCashier (
	ID INT, 
    FN VARCHAR(20),
    LN VARCHAR(20)
)
BEGIN
	DELETE FROM CASHIER WHERE cashierID = ID;
    DELETE FROM STAFF WHERE staffID = ID;
    DELETE FROM staffRecord WHERE isStaff = true AND isPatient=false AND staffID=ID AND firstName = FN AND lastName=LN;

END %%
DELIMITER ;


DROP Procedure IF EXISTS DeleteDoctor;
DELIMITER %%
CREATE PROCEDURE DeleteDoctor (
	ID INT, 
    FN VARCHAR(20),
    LN VARCHAR(20)
)
BEGIN
	DELETE FROM DOCTOR WHERE doctorID = ID;
    DELETE FROM STAFF WHERE staffID = ID;
    DELETE FROM staffRecord WHERE isStaff = true AND isPatient=false AND staffID=ID AND firstName = FN AND lastName=LN;

END %%
DELIMITER ;

DROP Procedure IF EXISTS DeleteRoom;
DELIMITER %%
CREATE PROCEDURE DeleteRoom (
	ID INT
)
BEGIN
	DELETE FROM ROOM WHERE roomID = ID;
END %%
DELIMITER ;

DROP Procedure IF EXISTS DeleteBill;
DELIMITER %%
CREATE PROCEDURE DeleteBill (
	ID INT
)
BEGIN
	DELETE FROM BILL WHERE billID = ID;
END %%
DELIMITER ;

DROP Procedure IF EXISTS DeletePatient;
DELIMITER %%
CREATE PROCEDURE DeletePatient (
	ID INT
)
BEGIN
	DELETE FROM PATIENT WHERE patientID = ID;
END %%
DELIMITER ;

DROP Procedure IF EXISTS DeleteMedicine;
DELIMITER %%
CREATE PROCEDURE DeleteMedicine (
	ID INT
)
BEGIN
	DELETE FROM MEDICINE WHERE medicineID = ID;
END %%
DELIMITER ;

DROP Procedure IF EXISTS DeleteRecord;
DELIMITER %%
CREATE PROCEDURE DeleteRecord (
	ID INT
)
BEGIN
	DELETE FROM RECORD WHERE recordID = ID;
END %%
DELIMITER ;
