USE HMS;

DROP Procedure IF EXISTS DeleteNurse;
DELIMITER %%
CREATE PROCEDURE DeleteNurse (
	ID INT
)
BEGIN
	DELETE FROM NURSE WHERE nurseID = ID;
    DELETE FROM STAFF WHERE staffID = ID;
    DELETE FROM RECORD WHERE isStaff = true AND isPatient=false;
END %%
DELIMITER ;

DROP Procedure IF EXISTS DeleteJanitor;
DELIMITER %%
CREATE PROCEDURE DeleteJanitor (
	ID INT
)
BEGIN
	DELETE FROM JANITOR WHERE janitorID = ID;
    DELETE FROM STAFF WHERE staffID = ID;
    DELETE FROM RECORD WHERE isStaff = true AND isPatient=false;
END %%
DELIMITER ;

DROP Procedure IF EXISTS DeleteCashier;
DELIMITER %%
CREATE PROCEDURE DeleteCashier (
	ID INT
)
BEGIN
	DELETE FROM CASHIER WHERE cashierID = ID;
    DELETE FROM STAFF WHERE staffID = ID;
    DELETE FROM RECORD WHERE isStaff = true AND isPatient=false;
END %%
DELIMITER ;

DROP Procedure IF EXISTS DeleteDoctor;
DELIMITER %%
CREATE PROCEDURE DeleteDoctor (
	ID INT
)
BEGIN
	DELETE FROM DOCTOR WHERE doctorID = ID;
    DELETE FROM STAFF WHERE staffID = ID;
    DELETE FROM RECORD WHERE isStaff = true AND isPatient=false;
END %%
DELIMITER ;
